name: spm

on:
  pull_request:
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

# This workflow builds and tests the Swift Package Manager. Only iOS runs on PRs
# because each platform takes 15-20 minutes after adding Firestore.

jobs:
  swift-build-run:
    runs-on: macOS-latest
    strategy:
      matrix:
        target: [iOS, tvOS, macOS, catalyst]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scripts Directory
      run: ./setup-scripts.sh
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: iOS Unit Tests
      run: scripts/third_party/travis/retry.sh scripts/build.sh GoogleUtilities-Package ${{ matrix.target }} spm
